all:
	sudo cp -r build/libftd2xx.so.1.4.6  /usr/local/lib
	sudo ln -s /usr/local/lib/libftd2xx.so.1.4.6 /usr/local/lib/libftd2xx.so 
	sudo chmod 0755 /usr/local/lib/libftd2xx.so.1.4.6 
	sudo rmmod ftdi_sio
	sudo rmmod usbserial

